M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Mon 30 Oct 2023 01:20:54 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-30T13:20:54-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X4.925Y-3.6
X4.925Y-3.8
T2
X4.6752Y-3.7
X4.7752Y-3.7
T3
X5.3364Y-3.572
X5.3364Y-3.828
X5.5136Y-3.572
X5.5136Y-3.828
T0
M30
